In [1]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [8]:
# code here
arr = np.array([[92,90,74],
    [6,63,93],
    [15,93,96],
    [70,60,48]])

#i
np.sort(arr)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [9]:
#ii
arr[:,1] =np.sort(arr[:,1])
arr

array([[92, 60, 74],
       [ 6, 63, 93],
       [15, 90, 96],
       [70, 93, 48]])

In [14]:
#iii
arr2 = np.array([[92,90,74],
    [6,63,93],
    [15,93,96],
    [70,60,48]])
row_max = arr2.max(axis=1)
indexes = row_max.argsort()[::-1]
arr2[indexes]

array([[15, 93, 96],
       [ 6, 63, 93],
       [92, 90, 74],
       [70, 60, 48]])

In [22]:
#iv
sorted_arr = np.sort(arr2, axis=None).reshape(arr2.shape)
print(sorted_arr)

[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [84]:
# code here
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]

# Step i
marks_with_extra = np.column_stack((marks, extra_subject))

# Step ii
all_marks = np.concatenate((marks_with_extra, [rec1, rec2]), axis=0)

# Step iii
marks_with_total = np.column_stack((all_marks, all_marks.sum(axis=1)))

# Step iv
sorted_marks = marks_with_total[marks_with_total[:, -1].argsort()[::-1]]
top2 = sorted_marks[:2]

print("After adding extra subject:\n", marks_with_extra)
print("\nAfter adding two extra students:\n", all_marks)
print("\nAfter adding total marks column:\n", marks_with_total)
print("\nAfter sorting on total marks:\n", sorted_marks)
print("\nTop 2 students:\n", top2)


After adding extra subject:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

After adding two extra students:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

After adding total marks column:
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

After sorting on total marks:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]

Top 2 students:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
np.unique(arr, axis=1) #row
np.unique(arr, axis=0) #col


array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [33]:
# code here
np.flip(arr)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [42]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

X = 6
indices =np.where(arr > X)
print(np.unique(indices[0]))

[1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [44]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
def convert(*arrays):
    merge = np.concatenate(arrays)
    return np.ravel(merge)

print(convert(arr1, arr2, arr3))

[0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [57]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
max = np.argmax(arr)
min = np.argmin(arr)
print(max, min)
deleted = np.delete(arr, [max, min])
arr


102 66


array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
# code here
arr = np.random.randint(100, 300, 200).reshape((20, 10))
arr

print(np.cumsum(st))



[  143   294   447   606   799   999  1199  1399  1599  1799  1999  2199
  2399  2599  2799  2999  3199  3399  3599  3799  3929  4090  4260  4458
  4658  4858  5058  5258  5458  5658  5763  5914  6068  6228  6417  6610
  6810  7010  7210  7410  7531  7667  7816  7967  8137  8337  8537  8737
  8937  9137  9238  9346  9463  9581  9711  9898 10098 10298 10498 10698
 10821 10982 11149 11324 11510 11710 11910 12110 12310 12510 12661 12828
 13010 13207 13407 13607 13807 14007 14207 14407 14508 14639 14794 14959
 15136 15328 15528 15728 15928 16128 16275 16424 16587 16758 16955 17155
 17355 17555 17755 17955 18068 18198 18339 18489 18672 18872 19072 19272
 19472 19672 19787 19928 20076 20256 20444 20637 20837 21037 21237 21437
 21543 21649 21800 21959 22124 22323 22523 22723 22923 23123 23264 23422
 23599 23799 23999 24199 24399 24599 24799 24999 25135 25289 25454 25632
 25812 26002 26202 26402 26602 26802 26907 27029 27221 27418 27618 27818
 28018 28218 28418 28618 28747 28883 29023 29163 29

In [75]:
#clip
cl = np.clip(arr, a_min=100, a_max=200)
cl

array([[193, 200, 200, 153, 200, 151, 143, 200, 159, 200],
       [200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
       [198, 200, 161, 200, 200, 200, 200, 200, 170, 130],
       [151, 200, 193, 200, 105, 154, 160, 189, 200, 200],
       [149, 200, 151, 200, 136, 121, 200, 200, 200, 170],
       [200, 200, 108, 118, 101, 200, 117, 200, 187, 130],
       [167, 200, 200, 186, 200, 200, 123, 161, 200, 175],
       [200, 200, 200, 200, 182, 200, 151, 197, 200, 167],
       [192, 200, 200, 200, 131, 177, 165, 155, 200, 101],
       [200, 163, 147, 200, 171, 149, 200, 200, 200, 197],
       [150, 141, 113, 200, 183, 130, 200, 200, 200, 200],
       [180, 193, 115, 200, 141, 188, 200, 200, 148, 200],
       [106, 200, 165, 106, 200, 199, 200, 159, 151, 200],
       [200, 200, 141, 158, 200, 200, 200, 200, 177, 200],
       [200, 200, 200, 165, 180, 200, 154, 190, 136, 178],
       [200, 200, 197, 200, 122, 200, 192, 200, 105, 200],
       [140, 200, 200, 200, 193, 200, 200, 136, 129, 140

In [77]:
#sort
st = np.sort(arr)
st

array([[143, 151, 153, 159, 193, 208, 208, 212, 229, 263],
       [206, 237, 252, 254, 260, 260, 267, 279, 290, 299],
       [130, 161, 170, 198, 221, 222, 231, 250, 257, 288],
       [105, 151, 154, 160, 189, 193, 230, 261, 266, 277],
       [121, 136, 149, 151, 170, 208, 219, 233, 234, 266],
       [101, 108, 117, 118, 130, 187, 218, 239, 288, 299],
       [123, 161, 167, 175, 186, 204, 217, 234, 238, 283],
       [151, 167, 182, 197, 205, 210, 218, 274, 286, 297],
       [101, 131, 155, 165, 177, 192, 229, 243, 252, 297],
       [147, 149, 163, 171, 197, 211, 212, 216, 256, 279],
       [113, 130, 141, 150, 183, 211, 232, 239, 264, 285],
       [115, 141, 148, 180, 188, 193, 228, 250, 261, 287],
       [106, 106, 151, 159, 165, 199, 205, 225, 241, 276],
       [141, 158, 177, 201, 223, 237, 250, 253, 268, 299],
       [136, 154, 165, 178, 180, 190, 232, 234, 261, 296],
       [105, 122, 192, 197, 207, 253, 269, 271, 282, 282],
       [129, 136, 140, 140, 193, 218, 227, 258, 264, 294

In [78]:
#cum sum
np.cumsum(st)

array([  143,   294,   447,   606,   799,  1007,  1215,  1427,  1656,
        1919,  2125,  2362,  2614,  2868,  3128,  3388,  3655,  3934,
        4224,  4523,  4653,  4814,  4984,  5182,  5403,  5625,  5856,
        6106,  6363,  6651,  6756,  6907,  7061,  7221,  7410,  7603,
        7833,  8094,  8360,  8637,  8758,  8894,  9043,  9194,  9364,
        9572,  9791, 10024, 10258, 10524, 10625, 10733, 10850, 10968,
       11098, 11285, 11503, 11742, 12030, 12329, 12452, 12613, 12780,
       12955, 13141, 13345, 13562, 13796, 14034, 14317, 14468, 14635,
       14817, 15014, 15219, 15429, 15647, 15921, 16207, 16504, 16605,
       16736, 16891, 17056, 17233, 17425, 17654, 17897, 18149, 18446,
       18593, 18742, 18905, 19076, 19273, 19484, 19696, 19912, 20168,
       20447, 20560, 20690, 20831, 20981, 21164, 21375, 21607, 21846,
       22110, 22395, 22510, 22651, 22799, 22979, 23167, 23360, 23588,
       23838, 24099, 24386, 24492, 24598, 24749, 24908, 25073, 25272,
       25477, 25702,

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [81]:
# code here
# Random array example
arr = np.random.rand(10)

# round to 3 decimals
arr_rounded = np.round(arr, 3)

# 0th and 100th percentile
p0 = np.percentile(arr_rounded, 0)
p100 = np.percentile(arr_rounded, 100)

print("Rounded array:", arr_rounded)
print("0th percentile == minimum value of the array??"," ", p0 == arr_rounded.min())
print("100th percentile == maximum value of the array??"," ", p100 == arr_rounded.max())

# Step 3: 50th & 51st percentile
p50 = np.percentile(arr_rounded, 50)
p51 = np.percentile(arr_rounded, 51)
diff = p51 - p50

print("50th percentile:", p50)
print("51st percentile:", p51)
print("Difference (51-50):", diff)


Rounded array: [0.785 0.541 0.507 0.859 0.913 0.987 0.361 0.504 0.357 0.493]
0th percentile == minimum value of the array??   True
100th percentile == maximum value of the array??   True
50th percentile: 0.524
51st percentile: 0.52706
Difference (51-50): 0.0030599999999999516
