**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
#Code here
np.zeros((5,2))

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [4]:
#Code here
a = int(input("Enter the number of rows"))
b = int(input("Enter the number of columns"))
np.random.random((a,b))

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [6]:
#Code here
a = int(input("Enter the number of rows"))
b = int(input("Enter the number of columns"))
mat = np.zeros((a,b), dtype=int)
for index,i in enumerate(mat):
        if index==0 or index==a-1:
            i[:]=1
        else:
            i[0]=1 
            i[-1]=1
mat    

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [7]:
#Code here
# np.linspace(start, stop, n) includes both start and stop by default
np.linspace(0,1,12)[1:-1]

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [8]:
#Code here
#No, identity matrix is possible only for the square natrix
np.identity(3)

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [9]:
#Code here
np.random.randint(0, 5, (5,5))

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [10]:
#code here
#To calculate the distance between two points in a 2D or 3D space, you can use the np.linalg.norm() function in NumPy.

random_vector = np.random.randint(1,101,(10,2))
point = np.array([2,3])
distances = np.round(np.linalg.norm(random_vector-point, axis=1)**2).astype(int)
distances

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [11]:
#Code here
# Mistake: Using np.where(array == list[99]) with floats
# Better: Use np.unravel_index(flat_index, shape)
# Why: It’s safe, exact, and doesn’t rely on float comparison

array = np.random.random((6, 7, 8))
# flat index
flat_index = 99
# convert to (x, y, z) tuple
index = np.unravel_index(flat_index, array.shape)

index

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [13]:
#Code here
numbers = input("Enter the numbers: ")

numbers = [float(x) for x in numbers.split()][::-1]

np.array(numbers)


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [14]:
#Code here
import random as r
intg = r.randint(1,100)
print(intg)
arr = np.random.random((intg,intg))
np.size(arr)


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [15]:
#Code here
def softmax(array):
    if not isinstance(array, np.ndarray) or array.ndim != 1:
        raise ValueError("Input must be a 1D NumPy array.")
    
    exp_values = np.exp(array)
    normalization_factor = np.sum(exp_values)
    softmax_values = exp_values / normalization_factor
    
    return softmax_values

array = np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])
softmax(array)

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [16]:
#Coder here
def vertical_stack(*arrays):
    if not all(isinstance(arr, np.ndarray) or arr.ndim != 1 for arr in arrays):
        raise ValueError("All input arrays must be NumPy arrays.")
    stacked_arrays = np.vstack(arrays)
    return stacked_arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

# Call the vertical_stack() function with the arrays
stacked_array = vertical_stack(array1, array2, array3)

print(stacked_array)

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [17]:
#Code here
from datetime import date, timedelta
def date_array(start, end):
    start = date.fromisoformat(start)
    end = date.fromisoformat(end)
    
    # Generate all dates
    delta = end - start
    all_dates = [(start + timedelta(days=i)).strftime('%Y-%m-%d') for i in range(delta.days + 1)]

    return all_dates
date_array(start = '2020-09-15', end = '2020-09-25')

###`Q-14:` Subtract the mean of each row from a matrix.

In [18]:
#code here
def subtract_mean_row(matrix):
    mean_row = np.mean(matrix, axis=1)
    subtracted_matrix = matrix - mean_row[:, np.newaxis]
    return subtracted_matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
subtracted_matrix = subtract_mean_row(matrix)
print(subtracted_matrix)

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [19]:
#Code here
def swap_column(matrix, col1, col2):
    if not isinstance(matrix, np.ndarray) or matrix.ndim != 2:
        raise ValueError("Input must be a 2D NumPy array.")
    
    if col1<0 or col1>=matrix.shape[1] or col2<0 or col2>=matrix.shape[1]: #shape[1] is the number of columns bcoz shape: (rows,columns)
        raise ValueError("Invalid column indices.")
    matrix[:, col1], matrix[:, col2] = matrix[:, col2], matrix[:, col1]
    return matrix
    
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
col1 = 0
col2 = 2
swapped_matrix = swap_column(matrix, col1, col2)
print(swapped_matrix)

In [20]:
# reference for the above question
a= np.array([[1,2,3],[4,5,6]]) 
a[0, 1] = a[1,1]
a


###`Q-16:` Replace odd elements in arrays with -1.

In [21]:
#Code here
def replace_odd(array):
    array[array % 2 != 0] = -1
    return array

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
replaced_array = replace_odd(array)
print(replaced_array)

In [ ]:
a=np.array([[1,2,3],[4,5,6]]) # for conecept revise of the above question
a%2==0

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
np.maximum(a, b)

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8, 5)

# Fetch every alternate column of the array
alternate_columns = arr1[:, ::2]

# Normalize the given array
normalized_arr = (arr1 - np.min(arr1)) / (np.max(arr1) - np.min(arr1))

print("Original array:")
print(arr1)

print("\nAlternate columns:")
print(alternate_columns)

print("\nNormalized array:")
print(normalized_arr)

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here
def n_largest(array,n):
    if not isinstance(array, np.ndarray) or n>len(array):
        raise ValueError("Invalid input.")
    sorted_array = np.sort(array)
    return sorted_array[n-1]

arr = np.array([12,34,40,7,1,0])
n=3
n_largest(arr,n)

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here

a = np.array([1, 2, 3])

pattern = np.tile(a, 3) # numpy.tile() function is used to repeat the input array a three times, resulting in an array with three copies of a
print(pattern)
pattern = np.repeat(pattern, 3) # numpy.repeat() function is used to repeat each element of pattern three times, resulting in an array with nine copies of a.

output = np.concatenate((pattern, np.tile(np.array([1, 2, 3]), 3))) #numpy.concatenate() function is used to concatenate the pattern array with three copies of the input array a, resulting in the desired pattern

output