### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([56, 54, 31, 17, 57, 66, 97, 90,  8,  4, 20, 61, 37, 76, 46])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[44, 16, 89, 49],
       [55, 87, 11, 60],
       [73, 39, 71, 43],
       [ 2,  3, 55, 48],
       [32, 78, 58, 57],
       [60, 93, 47, 17]])

In [5]:
np.sort(a)[::-1]

array([97, 90, 76, 66, 61, 57, 56, 54, 46, 37, 31, 20, 17,  8,  4])

In [6]:
# axis 0 - column and 1 - row
# syntax : np.sort(array, axis = 0/1)
np.sort(b,axis=0)

array([[ 2,  3, 11, 17],
       [32, 16, 47, 43],
       [44, 39, 55, 48],
       [55, 78, 58, 49],
       [60, 87, 71, 57],
       [73, 93, 89, 60]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:
# code
np.append(a,200)

array([ 56,  54,  31,  17,  57,  66,  97,  90,   8,   4,  20,  61,  37,
        76,  46, 200])

In [8]:
b

array([[44, 16, 89, 49],
       [55, 87, 11, 60],
       [73, 39, 71, 43],
       [ 2,  3, 55, 48],
       [32, 78, 58, 57],
       [60, 93, 47, 17]])

In [9]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[44.        , 16.        , 89.        , 49.        ,  0.53374719],
       [55.        , 87.        , 11.        , 60.        ,  0.25118068],
       [73.        , 39.        , 71.        , 43.        ,  0.31185727],
       [ 2.        ,  3.        , 55.        , 48.        ,  0.70859898],
       [32.        , 78.        , 58.        , 57.        ,  0.34456293],
       [60.        , 93.        , 47.        , 17.        ,  0.85990972]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [10]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [13]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array
- a:	NumPy array
- axis:	Jahan new dimension add karna hai


https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [15]:
# code
a.shape

(15,)

In [65]:
a

array([110, 530,  31,  17,  57,  66,  97,  90,   8,   4,  20,  61,  37,
        76,  46])

In [16]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [64]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [66]:
a

array([110, 530,  31,  17,  57,  66,  97,  90,   8,   4,  20,  61,  37,
        76,  46])

In [19]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  4,  5,  6,  7, 11, 13]),)

In [20]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 31, 17,  0,  0,  0,  0,  8,  4, 20,  0, 37,  0, 46])

In [21]:
np.where(a%2 == 0,0,a)

array([ 0,  0, 31, 17, 57,  0, 97,  0,  0,  0,  0, 61, 37,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [22]:
# code
a

array([56, 54, 31, 17, 57, 66, 97, 90,  8,  4, 20, 61, 37, 76, 46])

In [23]:
np.argmax(a)

np.int64(6)

In [24]:
b

array([[44, 16, 89, 49],
       [55, 87, 11, 60],
       [73, 39, 71, 43],
       [ 2,  3, 55, 48],
       [32, 78, 58, 57],
       [60, 93, 47, 17]])

In [25]:
np.argmax(b,axis=0)

array([2, 5, 0, 1])

In [26]:
np.argmax(b,axis=1)

array([2, 1, 0, 2, 1, 1])

In [27]:
# np.argmin
np.argmin(a)

np.int64(9)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [28]:
a

array([56, 54, 31, 17, 57, 66, 97, 90,  8,  4, 20, 61, 37, 76, 46])

In [29]:
np.cumsum(a)

array([ 56, 110, 141, 158, 215, 281, 378, 468, 476, 480, 500, 561, 598,
       674, 720])

In [30]:
b

array([[44, 16, 89, 49],
       [55, 87, 11, 60],
       [73, 39, 71, 43],
       [ 2,  3, 55, 48],
       [32, 78, 58, 57],
       [60, 93, 47, 17]])

In [31]:
np.cumsum(b,axis=1)

array([[ 44,  60, 149, 198],
       [ 55, 142, 153, 213],
       [ 73, 112, 183, 226],
       [  2,   5,  60, 108],
       [ 32, 110, 168, 225],
       [ 60, 153, 200, 217]])

In [32]:
np.cumsum(b)

array([  44,   60,  149,  198,  253,  340,  351,  411,  484,  523,  594,
        637,  639,  642,  697,  745,  777,  855,  913,  970, 1030, 1123,
       1170, 1187])

In [33]:
# np.cumprod
np.cumprod(a)

array([                 56,                3024,               93744,
                   1593648,            90837936,          5995303776,
              581544466272,      52339001964480,     418712015715840,
          1674848062863360,   33496961257267200, 2043314636693299200,
       1815665262813863936, 8863351457886797824, 1885797441182564352])

In [34]:
a

array([56, 54, 31, 17, 57, 66, 97, 90,  8,  4, 20, 61, 37, 76, 46])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [35]:
a

array([56, 54, 31, 17, 57, 66, 97, 90,  8,  4, 20, 61, 37, 76, 46])

In [36]:
np.percentile(a,50)

np.float64(54.0)

In [37]:
np.median(a)

np.float64(54.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [38]:
# code
a

array([56, 54, 31, 17, 57, 66, 97, 90,  8,  4, 20, 61, 37, 76, 46])

In [39]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [40]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [41]:
# code
a


array([56, 54, 31, 17, 57, 66, 97, 90,  8,  4, 20, 61, 37, 76, 46])

In [42]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([90, 20])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [43]:
# code
a

array([56, 54, 31, 17, 57, 66, 97, 90,  8,  4, 20, 61, 37, 76, 46])

In [44]:
np.flip(a)

array([46, 76, 37, 61, 20,  4,  8, 90, 97, 66, 57, 17, 31, 54, 56])

In [45]:
b

array([[44, 16, 89, 49],
       [55, 87, 11, 60],
       [73, 39, 71, 43],
       [ 2,  3, 55, 48],
       [32, 78, 58, 57],
       [60, 93, 47, 17]])

In [46]:
np.flip(b,axis=1)

array([[49, 89, 16, 44],
       [60, 11, 87, 55],
       [43, 71, 39, 73],
       [48, 55,  3,  2],
       [57, 58, 78, 32],
       [17, 47, 93, 60]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [47]:
# code
a

array([56, 54, 31, 17, 57, 66, 97, 90,  8,  4, 20, 61, 37, 76, 46])

In [48]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [49]:
# code
a

array([110, 530,  31,  17,  57,  66,  97,  90,   8,   4,  20,  61,  37,
        76,  46])

In [50]:
np.delete(a,[0,2,4])

array([530,  17,  66,  97,  90,   8,   4,  20,  61,  37,  76,  46])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [51]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
np.intersect1d(m,n)

array([3, 4, 5])

In [53]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
# symm diff
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [55]:
m[np.in1d(m,1)]

/tmp/ipython-input-524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [56]:
# code
a

array([110, 530,  31,  17,  57,  66,  97,  90,   8,   4,  20,  61,  37,
        76,  46])

In [57]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 31, 25, 57, 66, 75, 75, 25, 25, 25, 61, 37, 75, 46])

In [69]:
# np.swapaxes
# array.shape mein bs swap krdo..structure clear dikh jyega..baki 2d mein transpose ho jyega
a = np.array([[[1, 2, 3],
               [4, 5, 6]],

              [[7, 8, 9],
               [10, 11, 12]]])

swapped_a = np.swapaxes(a, 0, 1)

print(swapped_a)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [70]:
# np.random.uniform
# np.random.uniform(low, high, size)
# low → minimum value (inclusive)
# high → maximum value (exclusive)
# size → output shape
np.random.uniform(0, 1, 10) # 1D
np.random.uniform(0, 1, (3, 4)) # 2D
np.random.uniform(-1, 1, (2, 3, 4)) # 3D


array([[[-0.55894825,  0.21135508,  0.70297155, -0.91644153],
        [-0.73604557, -0.9965661 , -0.81555043, -0.68338422],
        [-0.69164511, -0.98818131, -0.9487303 , -0.55822495]],

       [[-0.28179004, -0.68285334, -0.2217476 , -0.6402899 ],
        [-0.7980103 ,  0.05185362, -0.9820632 ,  0.83111592],
        [-0.78262468,  0.19801973, -0.85694703,  0.09915731]]])

In [71]:
# np.count_nonzero
a = np.array([[0, 1], [2, 0]])

print(np.count_nonzero(a))

2


In [72]:
# np.tile
# np.tile(A, reps)
# A → input array
# reps → kitni baar repeat karna hai (int ya tuple)
a = np.array([1, 2, 3]) #1D
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [73]:
#2D
a = np.array([[1, 2],
              [3, 4]])

np.tile(a, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [75]:
#3D
a = np.array([[[1, 2]]])
np.tile(a, (2, 3, 4))

array([[[1, 2, 1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2, 1, 2]],

       [[1, 2, 1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2, 1, 2]]])

#### TILE VS REPEAT
- np.repeat([1,2,3], 2)   # [1 1 2 2 3 3]
- np.tile([1,2,3], 2)     # [1 2 3 1 2 3]

In [77]:
# np.repeat
# np.repeat(a, repeats, axis=None)
a = np.array([1, 2, 3])
np.repeat(a, 2)


array([1, 1, 2, 2, 3, 3])

In [76]:
np.repeat([1, 2, 3], [1, 2, 3])

array([1, 2, 2, 3, 3, 3])

In [78]:
a = np.array([[1, 2],
              [3, 4]])

np.repeat(a, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [79]:
np.repeat(a, 2) #axis=None by default → array flatten ho jata hai

array([1, 1, 2, 2, 3, 3, 4, 4])

### np.array_equal / == (Exact match)
Use when:
- Integers hain
- Ya floats jinme exact equality chahiye

Float case:

- a = np.array([0.1 + 0.2])
- b = np.array([0.3])
- np.array_equal(a, b)
False

In [80]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.0, 3.0])

np.array_equal(a, b)


True

### np.allclose (Numerical closeness)
Use when:
- Floating point numbers involved
- Small numerical error allowed

### Rule of thumb
- Integers / labels → array_equal
- Floating-point math → allclose

In [82]:
np.allclose(a, b)

True